### ISSUE TITLE
I will add superuser role support to the main pgtestdb repo

### ISSUE THREAD

**Issue by peterldowns** [kodergarten/pgtestdb#17]
Hey, I noticed that [the change you've made to give the pgtdbuser a superuser role](https://github.com/kodergarten/pgtestdb/commit/12d6d218d2a7f82805f4878f2c26add2373a0ed9) is pretty small. I'd like to support this use case in the main repo since being able to use extensions like postgis is pretty important. I'll open a PR soon, and if you're interested I'd love to have you test it and make sure that it works for your use case.

Regardless, you're absolutely welcome to maintain this fork — just thought I'd let you know. Thank you for using my software and please tell me if you have any other feedback, questions, feature requests, or suggestions!

**Comment by BrynBerkeley** [comment]
Hi Peter, thanks for creating this project. We needed to make this small tweak to get something working quickly and deployed. We would rather not have made this fork public. We hoped to contribute back once we had established this wasn't a case of user error and found some time to put together a proper solution. However, we'd love to test an official solution on the main project.

**Comment by peterldowns** [comment]
@BrynBerkeley here's a pull request that _might_ solve the problem you faced: https://github.com/peterldowns/pgtestdb/pull/6.  See the description and the updated docs for full details, but you can basically now pass a custom role with the `SUPERUSER` capability:

```go
// NewDB is a helper that returns an open connection to a unique and isolated
// test database, fully migrated and ready for you to query.
func NewDB(t *testing.T) *sql.DB {
  t.Helper()
  conf := pgtestdb.Config{
    DriverName: "pgx",
    User:       "postgres",
    Password:   "password",
    Host:       "localhost",
    Port:       "5433",
    Options:    "sslmode=disable",
    TestRole: &pgtestdb.Role{
        // This is the trick: tell pgtestdb to run migrations with a new role that has SUPERUSER capabilities.
        // You don't need to create this user, pgtestdb will create it for you. It used to do this underneath
        // the hood, now you can configure it.
        Username: "pgtdb-superuser"
        Password: pgtestdb.DefaultRolePassword,
        Capabilities: "SUPERUSER",
    },
  }
  // Replace this with whichever migrator you're actually using
  var migrator pgtestdb.Migrator = pgtestdb.NoopMigrator{}
  return pgtestdb.New(t, conf, migrator)
}
```

Your migrations will be run with this role, and everything should work — see
